# Librerias necesarias
library("ROAuth")
library("twitteR")
library("rtweet")
library("forecast")
library("tidyverse")
library("xlsx")
library("tm")
library("reshape2")
library("RColorBrewer")
library("wordcloud2")
library("wordcloud")
library("progress")
library("installr")
library("zip")
library("readxl")
library("knitr")
library("lubridate")
library("kableExtra")
library("tseries")
library("zoo")
library("ggfortify")
library("ggplot2")

